// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIb0a8-SByI8LqHSsGUulnK2-1o5pjrcQ',
    appId: '1:996861858800:web:b5cb1d0d73fe02ebc34335',
    messagingSenderId: '996861858800',
    projectId: 'taxiflex',
    authDomain: 'taxiflex.firebaseapp.com',
    storageBucket: 'taxiflex.appspot.com',
    measurementId: 'G-W1ZWGJMSQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPFF4o-StWypT8P9-OGNf-0gUDzgZUsdo',
    appId: '1:996861858800:android:1d248f49a891dc03c34335',
    messagingSenderId: '996861858800',
    projectId: 'taxiflex',
    storageBucket: 'taxiflex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc5FvH3KxndOsWnaF1VccXJ1nqQ4Uuxag',
    appId: '1:996861858800:ios:7da7e430af6fe24cc34335',
    messagingSenderId: '996861858800',
    projectId: 'taxiflex',
    storageBucket: 'taxiflex.appspot.com',
    iosClientId: '996861858800-dh351konvtrfpttkbm1fbq2t0kakc8n4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiflex',
  );
}
