name: snap_trash
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  camera: ^0.10.5+5
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  google_fonts: ^4.0.4
  google_nav_bar: ^5.0.6
  # location: ^5.0.3
  lottie: ^2.3.2
  # permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/