const cities = [
    'Beijing',
    'Delhi',
    'New York',
    'London',
    'Paris',
    'Tokyo',
    'Los Angeles',
    'Sydney',
    'Moscow',
    'Mumbai',
    'Shanghai',
    'Cairo',
    'Rio de Janeiro',
    'Rome',
    'Toronto',
    'Berlin',
    'Hong Kong',
    'Bangkok',
    'Singapore',
    'Dubai',
    'Istanbul',
    'Amsterdam',
    'Barcelona',
    'Chicago',
    'San Francisco',
    'Dublin',
    'Seoul',
    'Mexico City',
    'Cape Town',
    'Toronto',
    'Munich',
    'Stockholm',
    'Vienna',
    'New Delhi',
    'Prague',
    'Athens',
    'Buenos Aires',
    'Lisbon',
    'Helsinki',
    'Oslo',
    'Copenhagen',
    'Auckland',
    'Wellington',
    'Sao Paulo',
    'Budapest',
    'Warsaw',
    'Zurich',
    'Madrid',
    'Riyadh',
    'Johannesburg',
    'Lima',
    'Vancouver',
    'Montreal',
    'Amman',
    'Kuala Lumpur',
    'Manila',
    'Hanoi',
    'Nairobi',
    'Edinburgh',
    'Vienna',
    'Cologne',
    'Brussels',
    'Luxembourg',
    'Bucharest',
    'Ljubljana',
    'Reykjavik',
    'Tallinn',
    'Ljubljana',
    'Helsinki',
    'Riga',
    'Vilnius',
    'Kyiv',
    'Krakow',
    'Brisbane',
    'Perth',
    'Adelaide',
    'Brisbane',
    'Auckland',
    'Wellington',
    'Jakarta',
    'Manila',
    'Hanoi',
    'Kuala Lumpur',
    'Singapore',
    'Bangkok',
    'Mumbai',
    'Chennai',
    'Kolkata',
    'Dhaka',
    'Lahore',
    'Karachi',
    'Istanbul',
    'Ankara',
    'Izmir',
    'Antalya',
    'Izmir',
    'Dubai',
    'Abu Dhabi',
    'Doha',
    'Cairo',
    'Alexandria',
    'Casablanca',
    'Rabat',
    'Tunis',
    'Algiers',
    'Nairobi',
    'Cape Town',
    'Johannesburg',
    'Pretoria',
    'Durban',
    'Port Elizabeth',
];
export default cities;