# Generated by Django 4.2.6 on 2023-10-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0002_alter_account_email_alter_account_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
