# Generated by Django 4.2.6 on 2023-10-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0005_alter_businessaccount_images_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='business_account_images', to='Account_App.image'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='business_account_menu', to='Account_App.image'),
        ),
        migrations.AlterField(
            model_name='businessaccount',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='business_accounts', to='Account_App.review'),
        ),
    ]
