# Generated by Django 4.2.6 on 2023-10-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0006_alter_account_managers_alter_account_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='primage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='review',
            name='business_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_reviews', to='Account_App.businessaccount'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_reviews', to='Account_App.user'),
        ),
    ]
