# Generated by Django 4.2.6 on 2023-10-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account_App', '0007_businessaccount_primage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=models.ManyToManyField(blank=True, to='Account_App.image'),
        ),
    ]
