name: sustainable_living_guide
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-210.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.5.0 
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.1.14
  path_provider: ^2.1.1

  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  flutter_google_places_hoc081098: ^1.2.0
  google_api_headers: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.jpeg
    - assets/quotes.txt 

dependency_overrides:
  http: ^0.13.1  
  google_api_headers: ^2.0.3 
  rxdart: ^0.27.4




