// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBkXYNDJvYYevuLSNm9gpLoQ2_7hSURcjI",
      authDomain: "cds-turboroute.firebaseapp.com",
      projectId: "cds-turboroute",
      storageBucket: "cds-turboroute.appspot.com",
      messagingSenderId: "1034352884461",
      appId: "1:1034352884461:web:b21d72ccd2c9cea160eae4",
      measurementId: "G-MXQZJWDBSZ");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBiqVaXKXazguhJKytW1SJZo9FWJwWw1Y',
    appId: 'cds-turboroute',
    messagingSenderId: 'Place your key',
    projectId: 'cds-turboroute',
    storageBucket: 'cds-turboroute.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'Place your key',
    appId: 'Place your key',
    messagingSenderId: 'Place your key',
    projectId: 'Place your key',
    storageBucket: 'Place your key',
    androidClientId: 'Place your key',
    iosClientId: 'Place your key',
    iosBundleId: 'Place your key',
  );
}
